add unity-example
octopus-sensing/octopus-sensing pull request #56
Opened 2022-03-01 21:25 UTC by vegabs

2022-03-03 03:24 UTC, nastaran62 requested changes

2022-03-03 03:24 UTC, nastaran62 commented on examples/endpoint_unity_example/readme.md
> +
You are not using Octopus Sensing as the server. Octopus Sensing is a library. You have a server in python developed using the Octopus Sensing library.

2022-03-03 03:24 UTC, nastaran62 commented on examples/endpoint_unity_example/readme.md
> +![](ui-unity.jpg)
Which image?

2022-03-03 03:24 UTC, nastaran62 commented on examples/endpoint_unity_example/requestController.cs
> +        UnityWebRequest www = new UnityWebRequest("http://127.0.0.1:9331", "POST");
Please add comments for each of these lines

2022-03-03 03:24 UTC, nastaran62 commented on examples/endpoint_unity_example/requestController.cs
> +        startStimuli.onClick.AddListener(startRequest);
And add comments for this

2022-03-04 01:10 UTC, vegabs commented
I've added comments and the image

2022-03-09 01:45 UTC, merged